import { db } from '@/db';
import { transactions } from '@/db/schema';

async function main() {
    const currentTime = Math.floor(Date.now() / 1000);
    
    const sampleTransactions = [
        {
            userId: 'user_demo_001',
            cryptoSymbol: 'BTC',
            cryptoName: 'Bitcoin',
            transactionType: 'buy',
            amount: 0.3,
            pricePerUnit: 42000,
            totalValue: 12600,
            transactionDate: currentTime - 12960000,
            notes: 'Initial BTC purchase',
            createdAt: currentTime - 12960000,
        },
        {
            userId: 'user_demo_001',
            cryptoSymbol: 'BTC',
            cryptoName: 'Bitcoin',
            transactionType: 'buy',
            amount: 0.2,
            pricePerUnit: 48000,
            totalValue: 9600,
            transactionDate: currentTime - 7776000,
            notes: 'Added to BTC position',
            createdAt: currentTime - 7776000,
        },
        {
            userId: 'user_demo_001',
            cryptoSymbol: 'BTC',
            cryptoName: 'Bitcoin',
            transactionType: 'sell',
            amount: 0.1,
            pricePerUnit: 55000,
            totalValue: 5500,
            transactionDate: currentTime - 2592000,
            notes: 'Partial profit taking',
            createdAt: currentTime - 2592000,
        },
        {
            userId: 'user_demo_001',
            cryptoSymbol: 'ETH',
            cryptoName: 'Ethereum',
            transactionType: 'buy',
            amount: 3,
            pricePerUnit: 2600,
            totalValue: 7800,
            transactionDate: currentTime - 12960000,
            notes: 'Started ETH position',
            createdAt: currentTime - 12960000,
        },
        {
            userId: 'user_demo_001',
            cryptoSymbol: 'ETH',
            cryptoName: 'Ethereum',
            transactionType: 'buy',
            amount: 2,
            pricePerUnit: 3000,
            totalValue: 6000,
            transactionDate: currentTime - 5184000,
            notes: 'Increased ETH holdings',
            createdAt: currentTime - 5184000,
        },
        {
            userId: 'user_demo_001',
            cryptoSymbol: 'ETH',
            cryptoName: 'Ethereum',
            transactionType: 'sell',
            amount: 1,
            pricePerUnit: 3200,
            totalValue: 3200,
            transactionDate: currentTime - 1814400,
            notes: 'Sold 1 ETH for profit',
            createdAt: currentTime - 1814400,
        },
        {
            userId: 'user_demo_001',
            cryptoSymbol: 'SOL',
            cryptoName: 'Solana',
            transactionType: 'buy',
            amount: 50,
            pricePerUnit: 85,
            totalValue: 4250,
            transactionDate: currentTime - 10368000,
            notes: 'First SOL investment',
            createdAt: currentTime - 10368000,
        },
        {
            userId: 'user_demo_001',
            cryptoSymbol: 'SOL',
            cryptoName: 'Solana',
            transactionType: 'buy',
            amount: 50,
            pricePerUnit: 105,
            totalValue: 5250,
            transactionDate: currentTime - 5184000,
            notes: 'Doubled SOL position',
            createdAt: currentTime - 5184000,
        },
        {
            userId: 'user_demo_001',
            cryptoSymbol: 'SOL',
            cryptoName: 'Solana',
            transactionType: 'sell',
            amount: 20,
            pricePerUnit: 120,
            totalValue: 2400,
            transactionDate: currentTime - 1209600,
            notes: 'Took some profits on SOL',
            createdAt: currentTime - 1209600,
        },
        {
            userId: 'user_demo_001',
            cryptoSymbol: 'ADA',
            cryptoName: 'Cardano',
            transactionType: 'buy',
            amount: 3000,
            pricePerUnit: 0.40,
            totalValue: 1200,
            transactionDate: currentTime - 12960000,
            notes: 'Initial ADA buy',
            createdAt: currentTime - 12960000,
        },
        {
            userId: 'user_demo_001',
            cryptoSymbol: 'ADA',
            cryptoName: 'Cardano',
            transactionType: 'buy',
            amount: 2000,
            pricePerUnit: 0.50,
            totalValue: 1000,
            transactionDate: currentTime - 7776000,
            notes: 'Added more ADA',
            createdAt: currentTime - 7776000,
        },
        {
            userId: 'user_demo_001',
            cryptoSymbol: 'ADA',
            cryptoName: 'Cardano',
            transactionType: 'buy',
            amount: 1000,
            pricePerUnit: 0.48,
            totalValue: 480,
            transactionDate: currentTime - 2592000,
            notes: 'Small ADA addition',
            createdAt: currentTime - 2592000,
        },
    ];

    await db.insert(transactions).values(sampleTransactions);
    
    console.log('✅ Transactions seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});